In [2]:
import pandas as pd
from datetime import datetime
import seaborn as sns
import matplotlib.pyplot as plt

In [20]:

file = 'merged_data.csv'
df = pd.read_csv(file)

In [23]:
df = df.iloc[:,1:]

In [24]:
df

,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline,Day,Price Per Gallon
0,2020-02-15,-1.0,-2.0,11.0,8.0,-3.0,0.0,Saturday,3.125
1,2020-02-16,13.0,1.0,19.0,3.0,-2.0,-1.0,Sunday,3.125
2,2020-02-17,10.0,4.0,64.0,-13.0,-40.0,7.0,Monday,3.125
3,2020-02-18,4.0,2.0,51.0,6.0,-8.0,1.0,Tuesday,3.116
4,2020-02-19,2.0,2.0,62.0,6.0,-7.0,0.0,Wednesday,3.116
...,...,...,...,...,...,...,...,...,...
969,2022-10-11,-18.0,-10.0,24.0,-29.0,-40.0,9.0,Tuesday,NaN
970,2022-10-12,-19.0,-10.0,23.0,-33.0,-41.0,9.0,Wednesday,NaN
971,2022-10-13,-21.0,-10.0,10.0,-30.0,-41.0,9.0,Thursday,NaN
972,2022-10-14,-18.0,-9.0,16.0,-29.0,-44.0,9.0,Friday,NaN
973,2022-10-15,-19.0,-15.0,13.0,1.0,-16.0,1.0,Saturday,NaN