In [1]:
import pandas as pd
from datetime import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import calendar
from scipy.stats.stats import pearsonr
import numpy as np
from sklearn.utils import resample

# Checkpoint 2

In [2]:
king_county_2020 = pd.read_csv('2020_US_Region_Mobility_Report.csv')
king_county_2020 = king_county_2020[(king_county_2020.sub_region_1 == 'Washington') & (king_county_2020.sub_region_2 == 'King County')]

king_county_2021 = pd.read_csv('2021_US_Region_Mobility_Report.csv')
king_county_2021 = king_county_2021[(king_county_2021.sub_region_1 == 'Washington') & (king_county_2021.sub_region_2 == 'King County')]

king_county_2022 = pd.read_csv('2022_US_Region_Mobility_Report.csv')
king_county_2022 = king_county_2022[(king_county_2022.sub_region_1 == 'Washington') & (king_county_2022.sub_region_2 == 'King County')]

In [3]:
king_df = pd.concat([king_county_2020,king_county_2021,king_county_2022]).iloc[:, 8:15]

In [4]:
days = []
for i in range(len(king_df)):
    if i % 7 == 0:
        days.append("Saturday")
    elif i % 7 == 1:
        days.append("Sunday")
    elif i % 7 == 2:
        days.append("Monday")
    elif i % 7 == 3:
        days.append("Tuesday")
    elif i % 7 == 4:
        days.append("Wednesday")
    elif i % 7 == 5:
        days.append("Thursday")
    elif i % 7 == 6:
        days.append("Friday")
king_df["Day"] = days

In [5]:
king_df

,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline,Day
765150,2020-02-15,-1.0,-2.0,11.0,8.0,-3.0,0.0,Saturday
765151,2020-02-16,13.0,1.0,19.0,3.0,-2.0,-1.0,Sunday
765152,2020-02-17,10.0,4.0,64.0,-13.0,-40.0,7.0,Monday
765153,2020-02-18,4.0,2.0,51.0,6.0,-8.0,1.0,Tuesday
765154,2020-02-19,2.0,2.0,62.0,6.0,-7.0,0.0,Wednesday
...,...,...,...,...,...,...,...,...
704845,2022-10-11,-18.0,-10.0,24.0,-29.0,-40.0,9.0,Tuesday
704846,2022-10-12,-19.0,-10.0,23.0,-33.0,-41.0,9.0,Wednesday
704847,2022-10-13,-21.0,-10.0,10.0,-30.0,-41.0,9.0,Thursday
704848,2022-10-14,-18.0,-9.0,16.0,-29.0,-44.0,9.0,Friday
704849,2022-10-15,-19.0,-15.0,13.0,1.0,-16.0,1.0,Saturday

# US Energy Information Administration Fuel Prices for King County

In [6]:
fuel_prices = pd.read_csv('washington_gas_prices_2020-2022.csv')
fuel_prices = fuel_prices.loc[::-1].reset_index(drop=True)
fuel_prices

             Date  Price Per Gallon
0    Nov 21, 2022             4.822
1    Nov 14, 2022             4.901
2    Nov 07, 2022             4.879
3    Oct 31, 2022             4.934
4    Oct 24, 2022             5.049
..            ...               ...
146  Feb 03, 2020             3.108
147  Jan 27, 2020             3.107
148  Jan 20, 2020             3.142
149  Jan 13, 2020             3.134
150  Jan 06, 2020             3.181

[151 rows x 2 columns]

In [7]:
for index,date in enumerate(fuel_prices['Date']):
    fuel_prices['Date'][index] = datetime.strptime(date,"%b %d, %Y")
    
for index,date in enumerate(fuel_prices['Date']):
    fuel_prices['Date'][index] = date.strftime("%Y-%m-%d")
    
fuel_prices = fuel_prices.rename(columns={'Date':'date'})

/Users/alinaherri/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/alinaherri/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [8]:
fuel_prices

           date  Price Per Gallon
0    2022-11-21             4.822
1    2022-11-14             4.901
2    2022-11-07             4.879
3    2022-10-31             4.934
4    2022-10-24             5.049
..          ...               ...
146  2020-02-03             3.108
147  2020-01-27             3.107
148  2020-01-20             3.142
149  2020-01-13             3.134
150  2020-01-06             3.181

[151 rows x 2 columns]

In [9]:
combined = king_df.merge(fuel_prices,how='left',on='date')
combined[['Price Per Gallon']] = combined[['Price Per Gallon']].fillna(method='bfill')
combined['date'] = pd.to_datetime(combined['date'])
combined.sort_values(by='date')

,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline,Day,Price Per Gallon
0,2020-02-15,-1.0,-2.0,11.0,8.0,-3.0,0.0,Saturday,3.125
1,2020-02-16,13.0,1.0,19.0,3.0,-2.0,-1.0,Sunday,3.125
2,2020-02-17,10.0,4.0,64.0,-13.0,-40.0,7.0,Monday,3.125
3,2020-02-18,4.0,2.0,51.0,6.0,-8.0,1.0,Tuesday,3.116
4,2020-02-19,2.0,2.0,62.0,6.0,-7.0,0.0,Wednesday,3.116
...,...,...,...,...,...,...,...,...,...
969,2022-10-11,-18.0,-10.0,24.0,-29.0,-40.0,9.0,Tuesday,NaN
970,2022-10-12,-19.0,-10.0,23.0,-33.0,-41.0,9.0,Wednesday,NaN
971,2022-10-13,-21.0,-10.0,10.0,-30.0,-41.0,9.0,Thursday,NaN
972,2022-10-14,-18.0,-9.0,16.0,-29.0,-44.0,9.0,Friday,NaN
973,2022-10-15,-19.0,-15.0,13.0,1.0,-16.0,1.0,Saturday,NaN

# Multiple Hypothesis Testing

In [10]:
king_df["datetime"] = pd.to_datetime(king_df["date"])

In [11]:
king_df_weekly = king_df.groupby([pd.Grouper(key="datetime", freq="W-MON")]).mean().reset_index()
king_df_weekly

,datetime,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,2020-02-17,7.333333,1.000000,31.333333,-0.666667,-15.000000,2.000000
1,2020-02-24,2.428571,-1.142857,38.142857,3.857143,-3.428571,0.000000
2,2020-03-02,4.285714,3.714286,30.857143,3.285714,1.000000,-0.285714
3,2020-03-09,-6.142857,1.142857,24.142857,-15.000000,-12.428571,5.428571
4,2020-03-16,-17.285714,4.714286,22.142857,-33.000000,-28.000000,10.857143
...,...,...,...,...,...,...,...
135,2022-09-19,-16.142857,-9.285714,28.000000,-18.857143,-35.285714,6.142857
136,2022-09-26,-16.285714,-9.285714,29.714286,-19.428571,-35.142857,6.285714
137,2022-10-03,-14.857143,-9.428571,26.285714,-20.000000,-34.000000,6.285714
138,2022-10-10,-18.142857,-10.428571,18.714286,-23.285714,-33.714286,6.714286
139,2022-10-17,-19.000000,-10.800000,17.200000,-24.000000,-36.400000,7.400000

In [12]:
fuel_prices_weekly = fuel_prices.loc[::-1].reset_index(drop=True).iloc[6:,:]
fuel_prices_weekly["datetime"] = pd.to_datetime(fuel_prices_weekly["date"])
fuel_prices_weekly

           date  Price Per Gallon   datetime
6    2020-02-17             3.125 2020-02-17
7    2020-02-24             3.116 2020-02-24
8    2020-03-02             3.125 2020-03-02
9    2020-03-09             3.123 2020-03-09
10   2020-03-16             3.079 2020-03-16
..          ...               ...        ...
146  2022-10-24             5.049 2022-10-24
147  2022-10-31             4.934 2022-10-31
148  2022-11-07             4.879 2022-11-07
149  2022-11-14             4.901 2022-11-14
150  2022-11-21             4.822 2022-11-21

[145 rows x 3 columns]

In [13]:
df = fuel_prices_weekly.merge(king_df_weekly, on="datetime")
df

,date,Price Per Gallon,datetime,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,2020-02-17,3.125,2020-02-17,7.333333,1.000000,31.333333,-0.666667,-15.000000,2.000000
1,2020-02-24,3.116,2020-02-24,2.428571,-1.142857,38.142857,3.857143,-3.428571,0.000000
2,2020-03-02,3.125,2020-03-02,4.285714,3.714286,30.857143,3.285714,1.000000,-0.285714
3,2020-03-09,3.123,2020-03-09,-6.142857,1.142857,24.142857,-15.000000,-12.428571,5.428571
4,2020-03-16,3.079,2020-03-16,-17.285714,4.714286,22.142857,-33.000000,-28.000000,10.857143
...,...,...,...,...,...,...,...,...,...
135,2022-09-19,4.653,2022-09-19,-16.142857,-9.285714,28.000000,-18.857143,-35.285714,6.142857
136,2022-09-26,4.867,2022-09-26,-16.285714,-9.285714,29.714286,-19.428571,-35.142857,6.285714
137,2022-10-03,5.365,2022-10-03,-14.857143,-9.428571,26.285714,-20.000000,-34.000000,6.285714
138,2022-10-10,5.504,2022-10-10,-18.142857,-10.428571,18.714286,-23.285714,-33.714286,6.714286
139,2022-10-17,5.287,2022-10-17,-19.000000,-10.800000,17.200000,-24.000000,-36.400000,7.400000

In [14]:
pearsonr(df["Price Per Gallon"], df["retail_and_recreation_percent_change_from_baseline"])

(0.6173367269730554, 4.543380578986182e-16)

In [15]:
combined = combined.iloc[:-5, :]
combined

,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline,Day,Price Per Gallon
0,2020-02-15,-1.0,-2.0,11.0,8.0,-3.0,0.0,Saturday,3.125
1,2020-02-16,13.0,1.0,19.0,3.0,-2.0,-1.0,Sunday,3.125
2,2020-02-17,10.0,4.0,64.0,-13.0,-40.0,7.0,Monday,3.125
3,2020-02-18,4.0,2.0,51.0,6.0,-8.0,1.0,Tuesday,3.116
4,2020-02-19,2.0,2.0,62.0,6.0,-7.0,0.0,Wednesday,3.116
...,...,...,...,...,...,...,...,...,...
964,2022-10-06,-19.0,-8.0,17.0,-29.0,-40.0,9.0,Thursday,5.504
965,2022-10-07,-20.0,-10.0,21.0,-30.0,-43.0,9.0,Friday,5.504
966,2022-10-08,-22.0,-14.0,41.0,-6.0,-16.0,0.0,Saturday,5.504
967,2022-10-09,-11.0,-13.0,18.0,-6.0,-10.0,1.0,Sunday,5.504
968,2022-10-10,-21.0,-11.0,2.0,-31.0,-44.0,10.0,Monday,5.504

In [16]:
pearsonr(combined["Price Per Gallon"], combined["retail_and_recreation_percent_change_from_baseline"])

(0.5758018279193822, 1.1734845910638366e-86)

In [17]:
pearsonr(combined["Price Per Gallon"], combined["grocery_and_pharmacy_percent_change_from_baseline"])

(0.30064495469490726, 1.0808519630329646e-21)

In [18]:
pearsonr(combined["Price Per Gallon"], combined["parks_percent_change_from_baseline"])

(0.06659589197595082, 0.03820269213691178)

In [19]:
pearsonr(combined["Price Per Gallon"], combined["transit_stations_percent_change_from_baseline"])

(0.6329902090983905, 1.2771884506784533e-109)

In [20]:
pearsonr(combined["Price Per Gallon"], combined["workplaces_percent_change_from_baseline"])

(0.22308765850369305, 2.1531784586237947e-12)

In [21]:
pearsonr(combined["Price Per Gallon"], combined["residential_percent_change_from_baseline"])

(-0.5204596919545125, 2.2664358542811725e-68)

In [22]:
# From Lab 1 (Alina Herri)
def bonferroni(p_values, alpha_total):
    """
    Returns decisions on p-values using the Bonferroni correction.
    
    Inputs:
        p_values: array of p-values
        alpha_total: desired family-wise error rate (FWER = P(at least one false discovery))
    
    Returns:
        decisions: binary array of same length as p-values, where `decisions[i]` is 1
        if `p_values[i]` is deemed significant, and 0 otherwise
    """
    decisions = np.array(list(map(lambda p: p <= (alpha_total/len(p_values)), p_values)))
    return decisions

In [23]:
# From Lab 1 Solutions
def benjamini_hochberg(p_values, alpha):
    """
    Returns decisions on p-values using Benjamini-Hochberg.
    
    Inputs:
        p_values: array of p-values
        alpha: desired FDR (FDR = E[# false positives / # positives])
    
    Returns:
        decisions: binary array of same length as p-values, where `decisions[i]` is 1
        if `p_values[i]` is deemed significant, and 0 otherwise
    """
    n = len(p_values)
    sorted_p = np.sort(p_values)
    all_k = [k for k in range(n) if sorted_p[k] <= (k + 1) * (alpha / n)]
    if len(all_k) == 0:
        max_k = 0
    else:    
        max_k = max(all_k)
    threshold = sorted_p[max_k]
    decisions = p_values <= threshold
    return decisions

In [24]:
columns = ["retail_and_recreation_percent_change_from_baseline", "grocery_and_pharmacy_percent_change_from_baseline", "parks_percent_change_from_baseline", "transit_stations_percent_change_from_baseline", "workplaces_percent_change_from_baseline", "residential_percent_change_from_baseline"]
alpha = 0.05
for col in columns:
    print(col)
    p_values = []
    for i in range(1000):
        sample = resample(combined, replace=True, n_samples=100, random_state=i)
        p_value = pearsonr(sample["Price Per Gallon"], sample[col])[1]
        p_values.append(p_value)
    bonferroni_decisions = bonferroni(p_values, alpha)
    print("Bonferroni: " + str(len(bonferroni_decisions) - bonferroni_decisions.sum()))
    bh_decisions = benjamini_hochberg(p_values, alpha)
    print("BH: " + str(len(bh_decisions) - bh_decisions.sum()))

retail_and_recreation_percent_change_from_baseline
Bonferroni: 3
BH: 0
grocery_and_pharmacy_percent_change_from_baseline
Bonferroni: 860
BH: 104
parks_percent_change_from_baseline
Bonferroni: 1000
BH: 999
transit_stations_percent_change_from_baseline
Bonferroni: 1
BH: 0
workplaces_percent_change_from_baseline
Bonferroni: 963
BH: 488
residential_percent_change_from_baseline
Bonferroni: 39
BH: 0